// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-T01LpwSeTldcXHsYrGajTU_XcekDrO0',
    appId: '1:786464921191:web:fb4018a627cf04437fa6c2',
    messagingSenderId: '786464921191',
    projectId: 'databoard-e995b',
    authDomain: 'databoard-e995b.firebaseapp.com',
    storageBucket: 'databoard-e995b.firebasestorage.app',
    measurementId: 'G-K6KLXJJCPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBscl_pw2ntPQOW7uUzVx6zLOY7CYp-z5E',
    appId: '1:786464921191:android:211d4afc3c30186f7fa6c2',
    messagingSenderId: '786464921191',
    projectId: 'databoard-e995b',
    storageBucket: 'databoard-e995b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpOo9Nh9iWREcN4gwIsD7U_EmQHSWozsk',
    appId: '1:786464921191:ios:eba06d2bb47ba2dd7fa6c2',
    messagingSenderId: '786464921191',
    projectId: 'databoard-e995b',
    storageBucket: 'databoard-e995b.firebasestorage.app',
    iosBundleId: 'com.example.databoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpOo9Nh9iWREcN4gwIsD7U_EmQHSWozsk',
    appId: '1:786464921191:ios:eba06d2bb47ba2dd7fa6c2',
    messagingSenderId: '786464921191',
    projectId: 'databoard-e995b',
    storageBucket: 'databoard-e995b.firebasestorage.app',
    iosBundleId: 'com.example.databoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-T01LpwSeTldcXHsYrGajTU_XcekDrO0',
    appId: '1:786464921191:web:3246881de85792107fa6c2',
    messagingSenderId: '786464921191',
    projectId: 'databoard-e995b',
    authDomain: 'databoard-e995b.firebaseapp.com',
    storageBucket: 'databoard-e995b.firebasestorage.app',
    measurementId: 'G-59L101C746',
  );
}
